### ISSUE TITLE
USER STORY: Managing user data

### ISSUE THREAD

**Issue by johnvenkiah** [johnvenkiah/Agile-Testing#6]
As an administrator, I can access the information entered by users in the poll so that I better know how to structure the site in the future
  
# Acceptance Criteria
  
* Acceptance Criteria 1: The user data is stored in a structured file
* Acceptance Criteria 2: The file is easily accessible for staff members
* Acceptance Criteria 3: Missing user information does not create errors
  
# Tasks

- [ ] Task 1: Create web-based file for storage of poll data (for example a Google Sheet)
- [ ] Task 2: Make sure that only administrators can access this data
- [ ] Task 3: Write code to configure API to get data collection working
- [ ] Task 4:  Test the functionality
