### ISSUE TITLE
USER STORY: User Poll

### ISSUE THREAD

**Issue by johnvenkiah** [johnvenkiah/Agile-Testing#7]
As a user, I can fill in a poll about desired length, location and times for running so that administrators can revise users' preferences.
  
# Acceptance Criteria
  
* Acceptance Criteria 1: The poll is visible to users
* Acceptance Criteria 2: The poll contains fields for times, location and length for running
* Acceptance Criteria 3: Users are aware of their options to fill in the form or not
  
# Tasks

- [ ] Task 1: Design the poll pop-up window
- [ ] Task 2: Create the CSS, HTML and JS the feature needs
- [ ] Task 2.5: Complete tasks for associated stories
- [ ] Task 3: Test the poll's complete functionality
